decision:main.cpp
	g++ -o decision main.cpp Area.cpp mystd.cpp ReadAngle.cpp Step.cpp open.cpp -lssm -lm
cal_tanzaku_fac:cal_tanzaku_fac.cpp
	g++ -o cal_tanzaku_fac cal_tanzaku_fac.cpp -lglut -lGLU -lGL -lm
cal_w1:cal_w1.cpp
	g++ -o cal_w1 cal_w1.cpp -lglut -lGLU -lGL -lm
cal_wn:cal_wn.cpp
	g++ -o cal_wn cal_wn.cpp -lglut -lGLU -lGL -lm
cal_timezone_info:cal_timezone_info.cpp
	g++ -o cal_timezone_info cal_timezone_info.cpp -lglut -lGLU -lGL -lm -lssm
LS3DViewer:LS3DViewer.cpp
	g++ -o LS3DViewer LS3DViewer.cpp  -lglut -lGLU -lGL -lm -lssm
