decision:main.cpp
	g++ -o decision Area.cpp main.cpp mystd.cpp Tanzaku.cpp log_ctr.cpp Lane.cpp Step.cpp open.cpp -lssm -lm
spotR_GHI:spotR_GHI.cpp
	g++ -o spotR_GHI spotR_GHI.cpp -lglut -lGLU -lGL -lssm
spotR_ABCDEF:spotR_ABCDEF.cpp
	g++ -o spotR_ABCDEF spotR_ABCDEF.cpp -lglut -lGLU -lGL -lssm
cal_tanzaku_fac:cal_tanzaku_fac.cpp
	g++ -o cal_tanzaku_fac cal_tanzaku_fac.cpp -lglut -lGLU -lGL -lm
cal_w1:cal_w1.cpp
	g++ -o cal_w1 cal_w1.cpp -lglut -lGLU -lGL -lm
cal_wn:cal_wn.cpp
	g++ -o cal_wn cal_wn.cpp -lglut -lGLU -lGL -lm
